---
- name: Install Ansible Galaxy Roles
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get required roles with Ansible Galaxy
      ansible.builtin.command: "ansible-galaxy install -r {{ playbook_dir }}/../../requirements_4.example.yaml -p {{ playbook_dir }}/../../../roles"
      delegate_to: localhost
      changed_when: false
