---
- src: https://github.com/robertdebock/ansible-role-bootstrap
  name: robertdebock.bootstrap
  version: 6.0.0
- src: https://github.com/justin-p/ansible-role-update_package_cache
  name: robertdebock.update_package_cache
  version: justin-p-idempotent
- src: https://github.com/robertdebock/ansible-role-core_dependencies
  name: robertdebock.core_dependencies
  version: 2.1.9
- src: https://github.com/robertdebock/ansible-role-epel
  name: robertdebock.epel
  version: 3.1.5
- src: https://github.com/robertdebock/ansible-role-update
  name: robertdebock.update
  version: 3.1.3
- src: https://github.com/robertdebock/ansible-role-firewall
  name: robertdebock.firewall
  version: 5.1.4
- src: https://github.com/robertdebock/ansible-role-hostname
  name: robertdebock.hostname
  version: 3.1.4
- src: https://github.com/nginxinc/ansible-role-nginx
  name: nginxinc.nginx
  version: 0.23.1